import Providers from "@/components/layout/providers";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//get the page name and add it to the title
const header = headers();
const pathname = header.get("next-url");
const title = pathname === "/" ? "Sign In" : pathname.replace("/", "");
console.log(pathname);
export const metadata = {
  title: `${title} | Task Management System`,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
